# Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: clientserver
version: 0.1.0
description: A sample application showing App Engine code sharing between client and server.
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  appengine:
    git:
      url: https://github.com/domesticmouse/appengine.git
      ref: grpc
  gcloud: ^0.6.0+4
  http_server: ^0.9.8+1

dev_dependencies:
  build_runner: ^1.5.0
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

