name: contacts_server
version: 0.1.0-dev
dependencies:
  appengine:
    git:
      ref: v0.1
      url: https://github.com/dart-lang/appengine
  browser: any
  cloud_datastore:
    git:
      ref: v0.1
      url: https://github.com/dart-lang/cloud_datastore
  io_2014_contacts_demo: any
  polymer: '>=0.12.0 <0.13.0'
  shelf: any
  shelf_appengine:
    git:
      ref: 0-1-dev
      url: https://github.com/dart-lang/shelf_appengine
transformers:
- polymer:
    entry_points: web/index.html
